### ISSUE TITLE
feedback accelerate 2 workshop / 15-03-2022

### ISSUE THREAD

**Issue by foldingbeauty** [foldingbeauty/kelda#3]
placeholder for workshop participants to gather feedback of the Kelda workshop (15-03-2022)

**Comment by Bengelsoft** [comment]
Wat werkt er niet tijdens de workshop, en wat is het verbetervoorstel?
- Wachten op antwoorden van cursisten op gestelde vragen van docent;
- Timemanagement → planning volgen;
- Tooling is overkill voor de cursus →  Context geven van tooling;
- Voorbereiding van de workshop → opzetten omgeving, documentatie die gelezen kan worden als voorbereiding;
- Zaalverlichting, docent staat in het donker → Verlichting aanpassen op avond;
- Tijdens de opdrachten is het uitzoeken van informatie / context aan de korte kant;
- Uitgebreid eten tijdens de training;

Wat werkte er wel?
- Goede discussies;
- Creatieve aanpak van de training;
- Open karakter van de training;
- Fysieke aspect van om los te komen;
- Brownie als tastbaar voorbeeld;

Acties: Delen van interessante naslag op learningstone
