### ISSUE TITLE
feedback accelerate 2 workshop / 17-03-2022

### ISSUE THREAD

**Issue by foldingbeauty** [foldingbeauty/kelda#4]
placeholder for workshop participants to gather feedback of the Kelda workshop (17-03-2022)

**Comment by nmrsmn** [comment]
What didn't work;
- Learning / researching something new on the spot. Maybe give some literature for preparation
- Tijdstippen (overdag)
- Puzzelstukjes leggen, concreet voorbeeld bedenken -> Voorbereidend werk, langere intro over wat / waarom open source. 
- Witte scherm met silhouet
- Eerst open source definitie daarna bedrijfsnaam.
- Wat betekent governance nou?
- Onderzoeken meer focus geven

What did work;
- Warm-up games
- Sfeer en openheid
- Veel interactie en discussies
- Klassikaal op locatie
- Mooie locatie
- Mix en vorm planair
- Verdiepende links
- Veel mogelijkheden voor vragen
- Gouderak
- Brownie an sich
- Passie voor het onderwerp
- Enthousiaste groep. Blij met de discussies, de inzet en de hulp aan elkaar.
- Verbeter punten al door kunnen voeren waardoor ze niet meer terug kwamen.
- Catering en alles goed geregeld
